
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";



import AdminDashboard from "./pages/AdminDashboard.tsx";
import AdminSetup from "./pages/AdminSetup.tsx";
import AffiliateDashboard from "./pages/AffiliateDashboard.tsx";
import Analytics from "./pages/Analytics.tsx";
import App from "./pages/App.tsx";
import Dashboard from "./pages/Dashboard.tsx";
import Login from "./pages/Login.tsx";
import Logout from "./pages/Logout.tsx";
import Pricing from "./pages/Pricing.tsx";
import PrivacyPolicy from "./pages/PrivacyPolicy.tsx";
import Renew from "./pages/Renew.tsx";
import Settings from "./pages/Settings.tsx";
import Trades from "./pages/Trades.tsx";
import TradingJournal from "./pages/TradingJournal.tsx";

export const userRoutes: RouteObject[] = [



	{ path: "/admin-dashboard", element: <UserGuard><AdminDashboard /></UserGuard> },
	{ path: "/admindashboard", element: <UserGuard><AdminDashboard /></UserGuard> },
	{ path: "/admin-setup", element: <UserGuard><AdminSetup /></UserGuard> },
	{ path: "/adminsetup", element: <UserGuard><AdminSetup /></UserGuard> },
	{ path: "/affiliate-dashboard", element: <UserGuard><AffiliateDashboard /></UserGuard> },
	{ path: "/affiliatedashboard", element: <UserGuard><AffiliateDashboard /></UserGuard> },
	{ path: "/analytics", element: <UserGuard><Analytics /></UserGuard> },
	{ path: "/", element: <App /> },
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard> },
	{ path: "/login", element: <Login /> },
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard> },
	{ path: "/pricing", element: <Pricing /> },
	{ path: "/privacy-policy", element: <UserGuard><PrivacyPolicy /></UserGuard> },
	{ path: "/privacypolicy", element: <UserGuard><PrivacyPolicy /></UserGuard> },
	{ path: "/renew", element: <UserGuard><Renew /></UserGuard> },
	{ path: "/settings", element: <UserGuard><Settings /></UserGuard> },
	{ path: "/trades", element: <UserGuard><Trades /></UserGuard> },
	{ path: "/trading-journal", element: <UserGuard><TradingJournal /></UserGuard> },
	{ path: "/tradingjournal", element: <UserGuard><TradingJournal /></UserGuard> },

];
